name: FastAPI Local CI-CD

on:
  push:
    branches: ["main"] # Runs every time you push to the 'main' branch

jobs:
  continuous-integration:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Restart FastAPI Server
        env:
          RUNNER_TRACK_PROCESSES: false
        run: |
          # This command restarts the server with the latest code 
          # Note: your runner user might need NOPASSWD sudo access for this command
          sudo systemctl restart fastapi
          
          # Check status to make sure it's running
          systemctl status fastapi | grep "Active: active"